name: Recent Activity
on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes.
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repos README with recent activity
    steps:
      - uses: actions/checkout@v2
      - uses: ksharma20/github-activity-readme@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Updated README with recent activity"
          MAX_LINES: 5
